"use strict"
var INIT_BATTERY_ON=!0,INIT_BATTERY_OFF=!1,INIT_CONFORMANCE_ON=!0,INIT_CONFORMANCE_OFF=!1,INIT_HIGH_RES_ON=!0,INIT_HIGH_RES_OFF=!1,INIT_MODE_FREE="free",INIT_MODE_COMMUNITY="community",INIT_MODE_PRO="pro",INIT_MODE_CORPORATE="corporate",INIT_SAVE_NO=0,INIT_SAVE_PRIVATE=1,INIT_SAVE_PUBLIC=2,booleans=["OFF","ON"],databases=["Unavailable","Available"],saves=["Don't save","Private save","Public save"],suites=["All suites"],tests=["All tests"],powerBoard=null,hardwareBoard=null,systemInfo=null,config={battery:INIT_BATTERY_OFF,conformance:INIT_CONFORMANCE_ON,database:!1,high_res:INIT_HIGH_RES_OFF,mode:INIT_MODE_FREE,save:INIT_SAVE_PUBLIC,suite:0,suites:[],test:[0],tests:[],uid:null,browser:{name:null,version:null},device:{name:"Unknown",type:null},_device:{name:"Unknown",type:null},engine:{name:null,version:null},os:{name:null,version:null},resolution:{ratio:null,width:null,height:null,name:null},hardware:{},ready:!1}
Object.defineProperties(config,{database:{get:function(){return this._database},set:function(e){this._database=e,helper.UID()}},ready:{get:function(){return this._ready},set:function(e){this._ready=e,helper.launcher(),$("#start").removeClass("disabled")
var t=location.host+"/result/?"+config.uid
$("#results-url a").attr("href","http://"+t).html(t),1==e&&(helper.highRes(),helper.getStatus("mode",!1,function(){helper.getStatus("battery",!1,function(){helper.getStatus("conformance",!1,function(){process.launch()})})}),helper.getStatus("save"))}},mode:{get:function(){return this._mode},set:function(e){this._mode=e,e==INIT_MODE_PRO?$(".mode-pro").removeClass("mode-"+INIT_MODE_PRO):e==INIT_MODE_CORPORATE&&($(".mode-pro").removeClass("mode-"+INIT_MODE_PRO),$(".mode-corporate").removeClass("mode-"+INIT_MODE_CORPORATE)),this._mode!=INIT_MODE_FREE&&(helper.getStatus("suite"),helper.getSuites()),this._mode!=INIT_MODE_PRO&&this._mode!=INIT_MODE_CORPORATE||(helper.getStatus("test"),helper.getTests())}},battery:{get:function(){return this._battery},set:function(e){this._battery=e,e==INIT_BATTERY_ON&&this.save==INIT_SAVE_NO&&(this.save=INIT_SAVE_PRIVATE)}},browser:{get:function(){return this._browser.name+" "+this._browser.version},set:function(e){this._browser=e}},device:{get:function(){return this._device.name+" ("+this._device.type+")"},set:function(e){this._device=e}},engine:{get:function(){return this._engine.name+" "+this._engine.version},set:function(e){this._engine=e}},os:{get:function(){return this._os.name+" "+this._os.version},set:function(e){this._os=e}},resolution:{get:function(){return this._resolution.name},set:function(e){this._resolution=e}}})
var helper={database:function(){helper.setStatus("demo",0),$.getJSON("api/",function(e){config.database=e.database,powerBoard=e.powerBoard,hardwareBoard=e.hardwareBoard})},highRes:function(){var e="undefined"!=typeof performance.now()?1:0
helper.setStatus("high_res",e)},UID:function(){$.ajax({cache:!1,url:"api/results/uid/",dataType:"json",success:function(e){config.uid=e.uid
var t=sessionStorage.getItem("givenName")
null!=t&&helper.setStatus("device",t)
var n={browser:config._browser,engine:config._engine,os:config._os,resolution:config._resolution.name,device:config._device,hid:"undefined"!=typeof hid?hid:""}
$.ajax("api/systems/details",{data:{data:JSON.stringify(n)},method:"PUT"}).done(function(e){var t=JSON.parse(e)
"object"==typeof t.hardware&&(config.hardware=t.hardware)}),config.ready=!0}})},launcher:function(){"undefined"!=typeof hid&&""!=hid||"desktop"!=systemInfo.device.type||null==hardwareBoard||$.getJSON(hardwareBoard+"launchers/all",function(e){var t={windows:null,osx:null,linux:null}
$.each(e,function(e,n){"Windows"==n.os?t.windows=n.downloadUrl:"Mac OS X"==n.os?t.osx=n.downloadUrl:"Linux"==n.os&&(t.linux=n.downloadUrl)})
var n={windows:{url:t.windows,image:"/images/download_windows_button.png",name:"Windows"},osx:{url:t.osx,image:"/images/download_osx_button.png",name:"Mac OS X"},linux:{url:t.linux,image:"/images/download_linux_button.png",name:"Linux"}},i=n.windows.url,o=n.windows.image,a=n.windows.name,s=n.osx.url,r=n.osx.name,c=n.linux.url,l=n.linux.name,u=!1
switch(systemInfo.os.name){case"Windows":u=!0
break
case"OS X":i=n.osx.url,o=n.osx.image,a=n.osx.name,s=n.windows.url,r=n.windows.name,c=n.linux.url,l=n.linux.name,u=!0
break
case"Linux":case"Ubuntu":case"Kubuntu":case"Mint":i=n.linux.url,o=n.linux.image,a=n.linux.name,s=n.windows.url,r=n.windows.name,c=n.osx.url,l=n.osx.name,u=!0}u&&($("#launcher-dl-1").attr("href",i),$("#launcher-button").attr("src",o),$("#launcher-button").attr("alt","Download for "+a),$("#launcher-current-os").html(a),$("#launcher-dl-2").attr("href",s),$("#launcher-dl-2").html(r),$("#launcher-dl-3").attr("href",c),$("#launcher-dl-3").html(l),$("#launcher-ad, #launcher-not-using").removeClass("hidden"))})},getStatus:function(e,t,n){"undefined"==typeof t&&(t=!1),"undefined"==typeof n&&(n=function(e){}),$.getJSON("api/initializations/"+e,function(n){if("undefined"!=typeof n.active){if(t)return n.active
config[e]=n.active}}).done(n)},setStatus:function(e,t,n){"device"==e&&sessionStorage.setItem("givenName",t),"undefined"==typeof n&&(n=!1),$.post("api/initializations/"+e,{mode:t},function(t){return n?t:void("undefined"!=typeof t.active&&"device"!=e&&(config[e]=t.active))},"json")},getSuites:function(){$.getJSON("api/suites/all",function(e){config.suites=e,$.each(e,function(e,t){suites.splice(t.id,0,t.name+" "+t.version)})})},getTests:function(){$.getJSON("api/tests/all",function(e){config.tests=e,$.each(e,function(e,t){tests.splice(t.id,0,t.name+" "+t.version)})})}},process={launch:function(){this.urlListeners(),this.consoleAssistant(),this.onScreenAssistant()},consoleAssistant:function(){if(config.mode==INIT_MODE_COMMUNITY||config.mode==INIT_MODE_CORPORATE){this.consoleWriter("Basemark Web 3.0"),this.consoleWriter("Copyright (C) Basemark 2015. All rights reserved."),this.consoleWriter("Current configuration:")
var e=""+booleans[+config.battery]
if(config.battery&&(e+=", Results URL: http://"+location.host+"/result/?"+config.uid),this.consoleWriter("    Battery: "+e,!0),this.consoleWriter("    Conformance: "+booleans[+config.conformance],!0),this.consoleWriter("    Database: "+databases[+config.database],!0),this.consoleWriter("    High Resolution Timer: "+booleans[+config.high_res],!0),this.consoleWriter("    Mode: "+config.mode,!0),this.consoleWriter("    Save: "+saves[+config.save],!0),this.consoleWriter("    Suite: "+suites[+config.suite],!0),config.mode==INIT_MODE_CORPORATE){var t=[]
$.each(config.test,function(e,n){t.push(tests[n])}),this.consoleWriter("    Tests: "+t.join(", "),!0)}this.consoleWriter("Detection details:"),this.consoleWriter("   Browser: "+config.browser,!0),this.consoleWriter("   Engine: "+config.engine,!0),this.consoleWriter("   OS: "+config.os,!0),this.consoleWriter("   Resolution: "+config.resolution,!0)
var n=sessionStorage.getItem("givenName")
if(null==config._device.name||null!=n){var i=n||config.device
this.consoleWriter("   Device: "+i,!0)}else"mobile"==config._device.type&&this.consoleWriter("Define mobile device through http://"+location.host+"/?device=Your%20Device%20Model",!0)
if("undefined"!=typeof config.hardware.cpu){this.consoleWriter("   Hardware:",!0),this.consoleWriter("      CPU: "+config.hardware.cpu,!0),this.consoleWriter("      GPU: "+config.hardware.gpu,!0)
var o=0==config.hardware.memory.speed?(config.hardware.memory.amount+" "+config.hardware.memory.type).trim():(config.hardware.memory.speed+" MHz "+config.hardware.memory.amount+" "+config.hardware.memory.type).trim()
this.consoleWriter("      Memory: "+o,!0),this.consoleWriter("      Motherboard: "+config.hardware.motherboard.name,!0)}this.consoleWriter("Battery:"),this.consoleWriter("Change battery to "+booleans[+!config.battery]+": http://"+location.host+"/?battery="+ +!config.battery,!0),this.consoleWriter("Conformance:"),this.consoleWriter("Change conformance to "+booleans[+!config.conformance]+": http://"+location.host+"/?conformance="+ +!config.conformance,!0),this.consoleWriter("Suite options:"),$.each(suites,function(e,t){e!=config.suite&&process.consoleWriter("Select "+t+": http://"+location.host+"/?suite="+e,!0)}),config.mode==INIT_MODE_CORPORATE&&(this.consoleWriter("Test options:"),$.each(tests,function(e,t){"undefined"==typeof config.test[e]?process.consoleWriter("Activate "+t+": http://"+location.host+"/?test="+e,!0):0!=e&&process.consoleWriter("Deactivate "+t+": http://"+location.host+"/?test="+e,!0)}),this.consoleWriter("Save options:"),$.each(saves,function(e,t){e!=config.save&&process.consoleWriter(t+" the data: http://"+location.host+"/?save="+e,!0)})),this.consoleWriter("*** *"),this.consoleWriter("By executing the Basemark Web 3.0 you accept Terms of Service http://"+location.host+"/tos/",!0),this.consoleWriter("*** *"),this.consoleWriter("To launch benchmark, use URL http://"+location.host+"/run/",!0)}},consoleWriter:function(e,t){"undefined"==typeof t&&(t=!1),0==t&&(e="* "+e),console.info(e)},urlListeners:function(){var e=location.search.substr(1)
if(e){var t=e.split("&"),n={},i=null
$.each(t,function(e,t){var o=null,a=t.indexOf("=");-1!==a&&(o=t.substr(a+1),t=t.substr(0,a)),"mode"!==t?n[t]=o:i=o}),$.each(n,function(e,t){"hid"==e||("save"!=e&&"test"!=e||config.mode==INIT_MODE_CORPORATE?helper.setStatus(e,t):config.mode==INIT_MODE_COMMUNITY||config.mode==INIT_MODE_CORPORATE?helper.setStatus(e,t):"demo"==e&&helper.setStatus(e,t))}),i&&$.post("api/initializations/mode",{mode:i},function(e){location.href=location.protocol+"//"+location.host})}},onScreenAssistant:function(){function e(e,t,n){n=n||!1,e.val(t),1==t?(e.next(".on").css({zIndex:11}),e.prev(".off").css({zIndex:1})):(e.prev(".off").css({zIndex:11}),e.next(".on").css({zIndex:1})),n&&$.each(e,function(e,t){var n=$(t).attr("name"),i=$(t).data("id")
$.post("api/initializations/"+n,{mode:i})})}if($('#brand-heading span[data-mode="'+config.mode+'"]').css("display","inline-block"),$("#extended-information a").hover(function(){if(!$(this).hasClass("disabled")){var e=$(this).children("img")
e.attr("src",e.data("hover"))}},function(){if(!$(this).hasClass("disabled")){var e=$(this).children("img")
e.attr("src",e.data("disabled"))}}),$("#extended-information a").click(function(e){if(e.preventDefault(),$(this).tab("show"),!$(this).hasClass("disabled")){var t=$(this).children("img")
t.attr("src",t.data("enabled")),$(this).addClass("disabled")}}),$("#run-demo").click(function(e){e.preventDefault(),helper.setStatus("demo",1),setTimeout(function(){window.location="/run/"},300)}),$('a[data-toggle="tab"]').on("shown.bs.tab",function(e){var t=$(e.relatedTarget).children("img")
t.attr("src",t.data("disabled")),$(e.relatedTarget).removeClass("disabled")}),null==config._device.name||"apple iphone"==config._device.name.toLowerCase())if("mobile"==config._device.type){var t=sessionStorage.getItem("givenName")||""
$("#device-info .value").html('<input type="text" name="given-name" list="devices" value="'+t+'"><br><span class="smaller">We weren\'t enable to identify your device. Please describe us what is your device name to help us to categorize your result better. Thank you!</span><datalist id="devices"></datalist>'),powerBoard&&$.getJSON(powerBoard+"devices/all",function(e){$.each(e,function(e,t){"undefined"!=typeof t.oem&&$("#device-info .value datalist").append('<option value="'+t.oem.name+" "+t.name+'">')})})
var n
$("#device-info .value input").keydown(function(){$("#start").addClass("disabled")}),$("#device-info .value input").keyup(function(){clearTimeout(n)
var e=$(this).val()
e.length>2&&config._device.name!=e&&(n=setTimeout(function(){config._device.name=e,helper.setStatus("device",e),$("#start").removeClass("disabled")},2e3))})}else $("#device-info").hide(0)
else $("#device-info .value").html(config.device)
if($("#os-info .value").html(config.os),$("#browser-info .value").html(config.browser),$("#engine-info .value").html(config.engine),$("#resolution-info .value").html(config.resolution),$("#high_res-info .value").html(booleans[+config.high_res]),"undefined"!=typeof config.hardware.cpu){var i=""
i+="CPU: "+config.hardware.cpu+"<br>\n",i+="GPU: "+config.hardware.gpu+"<br>\n"
var o=0==config.hardware.memory.speed?(config.hardware.memory.amount+" "+config.hardware.memory.type).trim():(config.hardware.memory.speed+" MHz "+config.hardware.memory.amount+" "+config.hardware.memory.type).trim()
i+="Memory: "+o+"<br>\n",i+="Motherboard: "+config.hardware.motherboard.name+"<br>\n",$("#hardware-info .value").html(i),$("#hardware-info").removeClass("hidden")}var a="http://"+location.host+"/result/?"+config.uid,s=location.host+"/result/?"+config.uid
$("#battery-info div a").attr("href",a),$("#battery-info div a").html(s),$('input[name="conformance"]').val(+config.conformance),$('input[name="battery"]').val(+config.battery),config.battery&&$("#results-url").show(),$('select[name="save"]').val(config.save),config.save==INIT_SAVE_NO&&(e($('.range-input input[name="battery"]'),0),$('.range-input input[name="battery"]').attr("disabled",!0),$("#results-url").hide()),$('select[name="suite"]').val(config.suite),0!=config.suite&&($("#tests-suite-"+config.suite+'-config .range-input input[name="test"]').val(1),$('input[name="test"][data-id="0"]').val(0).attr("disabled",!1)),$.each(config.test,function(e,t){0!==t&&$('input[name="test"][data-id="'+t+'"]').val(1)})
var r=!0
$.each($('.range-input input[name="test"][data-id!="0"]'),function(e,t){0==$(t).val()&&(r=!1)}),r&&($('.range-input input[name="test"][data-id="0"]').val(1),e($('.range-input input[name="test"][data-id="0"]'),1)),$(".range-input input").each(function(){var t=$(this).val()
e($(this),t)}),$(".range-input input").change(function(t,n){n=n||{}
var i=$(this).val()
e($(this),i)
var o=$(this).attr("name"),a="undefined"!=typeof $(this).data("id")?$(this).data("id"):$(this).val()
if($.post("api/initializations/"+o,{mode:a}),$(this).attr("value",i),"test"==o)if("undefined"==typeof n.noSuiteChange&&($('select[name="suite"]').val(0),$.post("api/initializations/suite",{mode:0})),0==a&&1==i)$('.range-input input[name="test"][data-id!="0"]').val(1),e($('.range-input input[name="test"][data-id!="0"]'),1,!0)
else if(0==a&&0==i)$('.range-input input[name="test"][data-id!="0"]').val(0),e($('.range-input input[name="test"][data-id!="0"]'),0)
else if(0!=a&&1==i)e($('.range-input input[name="test"][data-id="0"]'),0)
else if(0!=a&&0==i){e($('.range-input input[name="test"][data-id="0"]'),0)
var s=$('.range-input input[name="test"][data-id!="0"]').filter(function(){return 1==$(this).val()}).length
0==s&&(e($('.range-input input[name="test"][data-id="0"]'),1),$('.range-input input[name="test"][data-id="0"]').attr("disabled",!0))}"battery"==o&&$("#results-url").toggle()}),$("select").change(function(){var t=$(this).attr("name"),n=$(this).val()
$.post("api/initializations/"+t,{mode:n}),"save"==t&&n==INIT_SAVE_NO?(e($('.range-input input[name="battery"]'),0),$('.range-input input[name="battery"]').attr("disabled",!0),$("#results-url").hide()):"save"==t&&n!=INIT_SAVE_NO?$('.range-input input[name="battery"]').attr("disabled",!1):"suite"==t&&0==n?($('.range-input input[name="test"][data-id!="0"][value="1"]').val(0).trigger("change",[{noSuiteChange:!0}]),$('.range-input input[name="test"][data-id="0"][value="0"]').val(1).trigger("change",[{noSuiteChange:!0}]),$('.range-input input[name="test"][data-id="0"]').attr("disabled",!0)):"suite"==t&&0!=n&&($('.range-input input[name="test"][value="1"]').val(0).trigger("change",[{noSuiteChange:!0}]),$('.range-input input[name="test"][data-id="0"]').attr("disabled",!1),$("#tests-suite-"+n+'-config .range-input input[name="test"][value="0"]').val(1).trigger("change",[{noSuiteChange:!0}]))})
var c=!1
$("span.select-arrow-down").click(function(e){var t=$(this).prev("select").get(0)
if(c)return void(c=!1)
c=!0
var n
return n=new MouseEvent("mousedown"),t.dispatchEvent(n),e.stopPropagation(),!1})}}
$(document).ready(function(){var e=window.devicePixelRatio||1
document.getElementById("dpi-test").offsetWidth*e
if(config.resolution={ratio:e,width:Math.round(screen.width),height:Math.round(screen.height),name:Math.round(screen.width*e)+"x"+Math.round(screen.height*e)},systemInfo=new WhichBrowser,null==systemInfo.browser.version&&null!=systemInfo.browser.alias){var t=systemInfo.browser.alias.split(" "),n=[]
$.each(t,function(e,t){0==isNaN(t)&&n.push(t)})
var i=n.join(".")}else if(null!=systemInfo.browser.version)var i=systemInfo.browser.version.original
else var i="0.0"
var o=""
if(null==systemInfo.engine.version&&null!=systemInfo.engine.alias){var a=systemInfo.engine.alias.split(" "),s=[]
$.each(a,function(e,t){0==isNaN(t)&&s.push(t)}),o=s.join(".")}else null!=systemInfo.engine.version&&(o=""+systemInfo.engine.version)
var r=null
if(null==systemInfo.os.version&&null!=systemInfo.os.alias){var c=systemInfo.os.alias.split(" "),l=[]
$.each(c,function(e,t){0==isNaN(t)&&l.push(t)})
var r=n.join(".")}else if(null!=systemInfo.os.version)var r=systemInfo.os.version.original
systemInfo.device.identified?config.device={name:""+systemInfo.device,type:systemInfo.device.type}:"undefined"!=typeof systemInfo.device.type&&(config.device={name:null,type:systemInfo.device.type}),config.browser={name:systemInfo.browser.name,version:i},config.engine={name:systemInfo.engine.name,version:o},config.os={name:systemInfo.os.version&&systemInfo.os.version.nickname?systemInfo.os.name+" "+systemInfo.os.version.nickname:systemInfo.os.name,version:r},helper.database()})
